INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('Cien años de soledad', 'Gabriel García Márquez', 1967);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('La fiesta del chivo', 'Mario Vargas Llosa', 2000);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('Crónicas de una muerte anunciada', 'Gabriel García Márquez', 1981);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('Pedro Páramo', 'Juan Rulfo', 1955);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('El laberinto de la soledad', 'Octavio Paz', 1950);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('El hobbit', 'J.R.R. Tolkien', 1937);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('El señor de los anillos', 'J.R.R. Tolkien', 1954);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('Canción de hielo y fuego', 'George R.R. Martin', 1996);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('Narnia, la travesía del viajero del Alva', 'C.S. Lewis', 1952);
INSERT INTO libros (titulo, autor, anio_publicacion) VALUES ('Cuentos de Terramar', 'Ursula K. Le Guin', 1968);